Change aware libs version to CxAalto:aware-client:HYKS-live-SNAPSHOT
- Matches what is used in HYKS app.  This may be causing build failures with this:
  Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
  > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/aware/providers/Screen_Provider$Screen_Data.class